/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airport;

import com.mysql.jdbc.Connection;
import java.awt.peer.PanelPeer;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.layout.Pane;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Form3_1 extends javax.swing.JFrame {

    /**
     * Creates new form form2
     */
    Connection con;
    public Form3_1() {
        initComponents();
        this.setLocationRelativeTo(null);
        buttonGroup1.add(rbtn_male);
        buttonGroup1.add(rbtn_female);
        
        try {
             con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/airport","root", "root");
        } catch (SQLException ex) {
            Logger.getLogger(Form3_1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt1_fname = new javax.swing.JTextField();
        txt2_lname = new javax.swing.JTextField();
        txt4_ssn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        rbtn_male = new javax.swing.JRadioButton();
        rbtn_female = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        date1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        com_nati = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_NO = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("first_name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(23, 15, 74, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("last_name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(301, 15, 71, 17);

        txt1_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1_fnameActionPerformed(evt);
            }
        });
        jPanel1.add(txt1_fname);
        txt1_fname.setBounds(115, 13, 114, 22);
        jPanel1.add(txt2_lname);
        txt2_lname.setBounds(390, 13, 149, 22);
        jPanel1.add(txt4_ssn);
        txt4_ssn.setBounds(115, 77, 114, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(441, 349, 70, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("SSN");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(23, 79, 74, 17);

        rbtn_male.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtn_male.setText("male");
        rbtn_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_maleActionPerformed(evt);
            }
        });
        jPanel1.add(rbtn_male);
        rbtn_male.setBounds(115, 134, 61, 25);

        rbtn_female.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtn_female.setText("female");
        jPanel1.add(rbtn_female);
        rbtn_female.setBounds(180, 134, 73, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("gender");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(23, 138, 74, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("DateOFBirth");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(12, 203, 85, 17);
        jPanel1.add(date1);
        date1.setBounds(115, 203, 138, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("nationality");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(12, 254, 85, 17);

        com_nati.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghan", "Albanian", "Algerian", "Argentine", "Australian", "Austrian", "Bangladeshi", "Belgian", "Bolivian", "Batswana", "Brazilian", "Bulgarian", "Cambodian", "Cameroonian", "Canadian", "Chilean", "Chinese", "Colombian", "Costa Rican", "Croatian", "Cuban", "Czech", "Danish", "Dominican", "Ecuadorian", "Egyptian", "Salvadorian", "English", "Estonian", "Ethiopian", "Fijian", "Finnish", "French", "German", "Ghanaian", "Greek", "Guatemalan", "Haitian", "Indian", "Iranian", "Iraqi", "Irish", "Italian", "Jamaican", "Japanese", "Jordanian", "Libyan", "Mexican", "Moroccan", "New Zealand", "Nigerian", "Pakistani", "Philippine", "Polish", "Russian", "Saudi", "South African", "Korean", "Spanish", "Syrian", "Taiwanese", "Tajikistani", "Thai", "Tongan", "Tunisian", "Turkish", "British" }));
        jPanel1.add(com_nati);
        com_nati.setBounds(115, 252, 138, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("phone_NO");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(12, 360, 85, 17);
        jPanel1.add(txt_NO);
        txt_NO.setBounds(115, 358, 138, 22);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\2.jpg")); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 550, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1_fnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            
            PreparedStatement stmt=con.prepareStatement("insert into passenger (pass_fname,pass_lname,pass_ssn,pass_gender,pass_nati,pass_no,pass_dateofbirth) values (?,?,?,?,?,?,?)");
            DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
            String s=df.format(date1.getDate());
            String ss="";
            if(rbtn_male.isSelected())
                ss="male";
            else if(rbtn_female.isSelected())
                ss="female";
            String sss=(String)com_nati.getSelectedItem();
            
            
            stmt.setString(1,txt1_fname.getText());
            stmt.setString(2,txt2_lname.getText());
            stmt.setDouble(3, Double.parseDouble(txt4_ssn.getText()));
            stmt.setString(4,ss);
            stmt.setString(5, sss);
            stmt.setString(6, txt_NO.getText());
            stmt.setString(7,s);
            stmt.executeUpdate();
            
            JOptionPane.showConfirmDialog(this, "data inserted");
            
            Form3_2 jfr=new Form3_2();
            this.setVisible(false);
            jfr.setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(Form3_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbtn_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_maleActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form3_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> com_nati;
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtn_female;
    private javax.swing.JRadioButton rbtn_male;
    public static javax.swing.JTextField txt1_fname;
    public static javax.swing.JTextField txt2_lname;
    private javax.swing.JTextField txt4_ssn;
    private javax.swing.JTextField txt_NO;
    // End of variables declaration//GEN-END:variables
}
