/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airport;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Dell
 */
public class Form4 extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    Connection con;
    DefaultTableModel dm = new DefaultTableModel();

    public Form4() {
        initComponents();
        this.setLocationRelativeTo(null);
        initComponents();
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/travel", "root", "root");

            dm.addColumn("N_Tribs");
            dm.addColumn("From1");
            dm.addColumn("To1");
            dm.addColumn("Depature");
            dm.addColumn("Arrived");

            jTable1.setModel(dm);
        } catch (SQLException ex) {
            Logger.getLogger(Form4.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    String from = "", to = "";

    public Form4(String x, String y) {
        initComponents();
        from = x;
        to = y;
        this.setLocationRelativeTo(null);
        initComponents();
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/travel", "root", "root");
            dm.addColumn("N_Tribs");
            dm.addColumn("From1");
            dm.addColumn("To1");
            dm.addColumn("Depature");
            dm.addColumn("Arrived");

            jTable1.setModel(dm);
        }catch (SQLException ex) {
            Logger.getLogger(Form4.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form4 Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 367, 95, 42);

        jButton2.setText("Load");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(45, 369, 87, 40);

        jTable1.setModel(dm);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 530, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airport/6.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 530, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        /*int row_num=jTable1.getSelectedRow();
        
        DefaultTableModel obj=(DefaultTableModel) jTable1.getModel();
        
        String s1=obj.getValueAt(row_num,3).toString();
        String s2=obj.getValueAt(row_num,4).toString();
        
        JOptionPane.showMessageDialog(this, s1+"   "+s2);
        */
        Form5 frm = new Form5();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /*
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PreparedStatement stmt;
        try {
            stmt = con.prepareStatement("SELECT * FROM time_lines where From1 =? and To1=?");
            //JOptionPane.showMessageDialog(this, from);
            //JOptionPane.showMessageDialog(this, to);
            stmt.setString(1, from);
            stmt.setString(2, to);
            ResultSet rs = stmt.executeQuery();

            
            while (rs.next()) {
                String[] s={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                //JOptionPane.showMessageDialog(this, s);
                dm.addRow(s);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Form4.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        /*int i=0;
        i=jTable1.getSelectedRow();
        TableModel mod=jTable1.getModel();
        String s1=mod.getValueAt(i,3).toString();
        JOptionPane.showMessageDialog(this, s1);*/
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
